server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
security:
  jwt:
    secret: my-super-secret-key
logging:
  pattern:
    console: "%d %-5level [%thread] %logger{36} - %msg trace=%X{traceId}%n"
