server: { port: 8085 }
spring:
  application: { name: order-service }
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Thenu@5612}
  jpa: { hibernate: { ddl-auto: update } }
  kafka: { bootstrap-servers: kafka:9092 }
eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka/
feign.client.config.default.connectTimeout: 5000
