server: { port: 8082 }
spring:
  application: { name: product-service }
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://mysql:3306/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa: { hibernate: { ddl-auto: update } }
eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka/
